In [2]:
import numpy as np

In [3]:
len(dir(np)) # no of funcs in numpy

618

In [4]:
a = np.array([[3,4,5],
             [0,1,2]])
b = np.array([[7,8,9],
             [2,8,0]])             

In [5]:
np.sort(b, axis=1)   # sort in axis = 1 default for 2d out of two axis
np.sort(b, axis=0)   # sort in axis = 0 default for 1d as only 1 axis

array([[2, 8, 0],
       [7, 8, 9]])

In [6]:
np.sum(a, axis=0)     # lower the value higher priority in heirarchy or complexer is addition
np.sum(a, axis=1)

array([12,  3])

In [7]:
# a.dot(a.transpose())
# b.dot(a.transpose())
# a.dot(b.transpose()) # transpose is needed to fulfil pxn & nxq validity for matrix multiply
#  ---- OR ----
np.dot(a, b.transpose())

array([[98, 38],
       [26,  8]])

In [8]:
np.cross(a, b)

array([[ -4,   8,  -4],
       [-16,   4,  -2]])

In [9]:
c = np.arange(10)  # same as that of array for i in range form
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
d = np.array([50,34,55,54,66,2,1,43,3,5,34,35,24,85,47,76,80,8])
d.shape

(18,)

In [11]:
# d.reshape(2,9)
# d.reshape(6,3)  # change current shape 

In [12]:
np.sort(d)

array([ 1,  2,  3,  5,  8, 24, 34, 34, 35, 43, 47, 50, 54, 55, 66, 76, 80,
       85])

In [13]:
np.argsort(d)   # print position of elem when sorted

array([ 6,  5,  8,  9, 17, 12,  1, 10, 11,  7, 14,  0,  3,  2,  4, 15, 16,
       13], dtype=int32)

In [14]:
np.argmin(d) # position of min elem

6

In [15]:
np.argmax(d) # position of max elem

13

In [16]:
'''
Input: vect_A[] = {3, -5, 4}
        vect_B[] = {2, 6, 5}
Output: Dot product: -4
         Cross product = -49 -7 28
'''
c = [3,-5,4]
d = [2,6,5]
print(np.dot(c,d))
print(np.cross(c,d))

-4
[-49  -7  28]
