-----------------------------  Basic Funcs -----------------------------------

In [2]:
import numpy as np
arr1 = np.array([3,3,1,5.6], dtype='int32')  # else dtype will be float as 5.6 is there
arr2 = np.array([[3,3,1,5,1], [2,7,8,9,12]])
print(arr1)
print(arr2)
print(type(arr1))

[3 3 1 5]
[[ 3  3  1  5  1]
 [ 2  7  8  9 12]]
<class 'numpy.ndarray'>


In [3]:
print(arr1.shape) # structure
print(arr2.shape) # structure
print(arr1.dtype) # datatypes
print(arr2.dtype) # datatypes
print(arr2.size) # no of elems

(4,)
(2, 5)
int32
int32
10


In [4]:
print(np.zeros((4)))
print(np.zeros((4,6)))
print(np.zeros((2,2,2)))

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [5]:
np.empty((4,6))   # same as np.zeros but simplest form of arr... with garbage values instead of zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
print(np.ones(4))
print(np.ones((2,3)))

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr2

array([[ 3,  3,  1,  5,  1],
       [ 2,  7,  8,  9, 12]])

In [8]:
arr2*arr2   # same for other operations 

array([[  9,   9,   1,  25,   1],
       [  4,  49,  64,  81, 144]])

In [9]:
arr2+arr2

array([[ 6,  6,  2, 10,  2],
       [ 4, 14, 16, 18, 24]])

In [10]:
arr2/2

array([[1.5, 1.5, 0.5, 2.5, 0.5],
       [1. , 3.5, 4. , 4.5, 6. ]])

--------------------------------- Slicing -------------------------------

In [11]:
arr = np.array([4,3,74,32])
arr

array([ 4,  3, 74, 32])

In [12]:
a1 = arr[2:4].copy()  # in absence of .copy() original arr shall be changed
a1

array([74, 32])

In [13]:
a1[0] = 0
arr     # in absence of .copy() original arr shall be changed

array([ 4,  3, 74, 32])

In [14]:
arr2[1,3] # print second sub array 4th element
arr2[1,3:4] # print second sub array 4th element using slicing

array([9])

In [15]:
# c = np.linspace(start,stop,no of no.s b/w start & stop)
c = np.linspace(4,7,10)
c

array([4.        , 4.33333333, 4.66666667, 5.        , 5.33333333,
       5.66666667, 6.        , 6.33333333, 6.66666667, 7.        ])

In [16]:
arr5 = arr2.ravel()
arr5   # convert any array to 1d array

array([ 3,  3,  1,  5,  1,  2,  7,  8,  9, 12])

In [19]:
arr6 = np.sqrt(arr5)
arr6

array([1.73205081, 1.73205081, 1.        , 2.23606798, 1.        ,
       1.41421356, 2.64575131, 2.82842712, 3.        , 3.46410162])

In [21]:
np.where(arr6>2.5)   # position of elem where the condition is satisfied

(array([6, 7, 8, 9], dtype=int32),)